const styles = {
    heroSection: {
      bgcolor: 'primary.main',
      p: 4,
      textAlign: 'center' as const,
      width: '100vw',
      position: 'relative' as const,
      left: '50%',
      right: '50%',
      marginLeft: '-50vw',
      marginRight: '-50vw',
      height: '60vh',
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundImage: 'url("/hero_gamevault.png")',
      backgroundSize: 'cover',
      backgroundPosition: 'center',
      backgroundColor: 'rgba(26, 26, 29, 0.85)', // Semi-transparent overlay
      backgroundBlendMode: 'overlay',
    },
    sectionLight: {
      bgcolor: 'background.paper',
      p: 4,
      width: '100vw',
      position: 'relative' as const,
      left: '50%',
      right: '50%',
      marginLeft: '-50vw',
      marginRight: '-50vw',
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sectionDark: {
      bgcolor: 'primary.dark',
      p: 4,
      textAlign: 'center' as const,
      width: '100vw',
      position: 'relative' as const,
      left: '50%',
      right: '50%',
      marginLeft: '-50vw',
      marginRight: '-50vw',
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'center',
      alignItems: 'center',
    },
    featureCard: {
      p: 4,
      bgcolor: 'background.default',
      display: 'flex',
      flexDirection: 'column' as const,
      justifyContent: 'center',
      alignItems: 'center',
      textAlign: 'center' as const,
    },
    footer: {
      bgcolor: 'secondary.main',
      color: 'text.primary',
      p: 2,
      mt: 'auto',
      width: '100%',
    },
  };
  
  export default styles;
  