const styles = {
	heroSection: {
		bgcolor: 'primary.main',
		p: 4,
		textAlign: 'center' as const,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		height: '60vh',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundImage: 'url("/hero_gamevault.png")',
		backgroundSize: 'cover',
		backgroundPosition: 'center',
		backgroundColor: 'rgba(26, 26, 29, 0.85)', // Semi-transparent overlay
		backgroundBlendMode: 'overlay',
	},
	sectionLight: {
		bgcolor: 'background.paper',
		p: 4,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
	},
	sectionDark: {
		bgcolor: 'primary.dark',
		p: 4,
		textAlign: 'center' as const,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
	},
    marquee: {
		display: 'flex',
		flexDirection: 'row',
		flexWrap: 'nowrap' as const,
		overflow: 'hidden',
		whiteSpace: 'nowrap' as const,
		animation: 'marquee 80s linear infinite',
		'&:hover': {
			animationPlayState: 'paused',
		},
		'@keyframes marquee': {
			'0%': { transform: 'translateX(0%)' },
			'100%': { transform: 'translateX(-50%)' },
		},
	},
	card: {
		width: 250,
		marginRight: 3, 
	},
	featureCard: {
		padding: 2,
		textAlign: 'left' as const,
	},
	footer: {
		bgcolor: 'secondary.main',
		color: 'text.primary',
		p: 2,
		mt: 'auto',
		width: '100%',
	},
};

export default styles;
