const styles = {
	heroSection: {
		bgcolor: 'primary.main',
		p: 4,
		textAlign: 'center' as const,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		height: '60vh',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundImage: 'url("/hero_gamevault.png")',
		backgroundSize: 'cover',
		backgroundPosition: 'center',
		backgroundColor: 'rgba(26, 26, 29, 0.85)', // Semi-transparent overlay
		backgroundBlendMode: 'overlay',
	},
	sectionLight: {
		bgcolor: 'background.paper',
		p: 4,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
	},
	sectionDark: {
		bgcolor: 'primary.dark',
		p: 4,
		textAlign: 'center' as const,
		width: '100vw',
		position: 'relative' as const,
		left: '50%',
		right: '50%',
		marginLeft: '-50vw',
		marginRight: '-50vw',
		display: 'flex',
		flexDirection: 'column' as const,
		justifyContent: 'center',
		alignItems: 'center',
	},
	marquee: {
		display: 'flex',
		flexDirection: 'row',
		flexWrap: 'nowrap' as const,
		overflow: 'hidden',
		whiteSpace: 'nowrap' as const,
		animation: 'marquee 60s linear infinite', // Slower animation
		'&:hover': {
			animationPlayState: 'paused',
		},
		'@keyframes marquee': {
			'0%': { transform: 'translateX(100)' },
			'100%': { transform: 'translateX(-100%)' },
		},
	},
	card: {
		width: '250px',
		height: '350px', // Adjust the height as needed
		margin: '0 8px', // Add margin to space out the cards
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
	  },
	truncatedText: {
		overflow: 'hidden',
		display: 'webkitBox',
		'webkitLineClamp': 2,
		'webkitBoxOrient': 'vertical',
		textOverflow: 'ellipsis',
	},
	featureCard: {
		padding: 4,
		textAlign: 'left' as const,
	},
	footer: {
		bgcolor: 'primary.main',
		color: 'text.primary',
		p: 2,
		mt: 'auto',
		width: '100%',
	},
};

export default styles;
